# -*- coding: utf-8 -*-
"""Proses sql statement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17aYDScleQ6Dew6Ib6w17ODMZYJdork2L
"""

import pandas as pd

# Baca file Excel
file_path = '/content/Analisis Sentimen Topik Ulasan Cafe R57.xlsx' #lokasi path file
sheet_name = 0
data = pd.read_excel(file_path, sheet_name=sheet_name)

# Sesuaikan nama kolom
columns_needed = ['Nama Pengulas', 'Rating Bintang', 'Teks Ulasan', 'Topik Utama', 'Sentimen', 'Nama Cafe']
data = data[columns_needed]

# Validasi sentimen
valid_sentiments = ['Positif', 'Negatif', 'Netral']

# Membuat SQL Insert statements
sql_statements = []
for index, row in data.iterrows():
    nama_pengulas = row['Nama Pengulas'].replace("'", "''")  # Escape single quotes
    rating_bintang = row['Rating Bintang']
    teks_ulasan = row['Teks Ulasan'].replace("'", "''")
    topik_utama = row['Topik Utama'].replace("'", "''")
    nama_cafe = row['Nama Cafe'].replace("'", "''")

    # Validasi dan format sentimen
    sentimen = row['Sentimen'].strip().title()
    if sentimen not in valid_sentiments:
        sentimen = 'Neutral'  # Default jika nilai tidak valid

    sql = (
        f"INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) "
        f"VALUES ('{nama_pengulas}', {rating_bintang}, '{teks_ulasan}', '{topik_utama}', '{sentimen}', '{nama_cafe}');"
    )
    sql_statements.append(sql)

# Menulis perintah SQL ke file
output_file = 'insert_statements_r57.sql' #nama file
with open(output_file, 'w', encoding='utf-8') as f:
    f.write("\n".join(sql_statements))

print(f"SQL statements berhasil dibuat dan disimpan di: {output_file}")