# -*- coding: utf-8 -*-
"""Proses pelabelan data rekomendasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7v_3hoGTBM_K4jtWxvZbltD3yNAlGgX
"""

from itertools import product
from openpyxl import Workbook
from openpyxl.utils import get_column_letter

def create_excel_with_combinations():
    # Define the codes
    kode_a = ['a.a', 'a.b', 'a.c', 'a.d']
    kode_b = ['b.a', 'b.b', 'b.c']
    kode_c = ['c.a', 'c.b']
    kode_d = ['d.a', 'd.b', 'd.c', 'd.d']

    # Generate all combinations
    combinations = list(product(kode_a, kode_b, kode_c, kode_d))

    # Create a workbook and active worksheet
    wb = Workbook()
    ws = wb.active
    ws.title = "Combinations"

    # Write headers
    headers = ["Kode A", "Kode B", "Kode C", "Kode D", "Rumus"]
    ws.append(headers)

    # Write combinations to the sheet
    for row_index, combination in enumerate(combinations, start=2):
        ws.append(list(combination))

        # Determine cell references for the current row
        n3 = f"N{3 + (kode_a.index(combination[0]))}"
        n9 = f"N{9 + (kode_b.index(combination[1]))}"
        n14 = f"N{14 + (kode_c.index(combination[2]))}"
        n18 = f"N{18 + (kode_d.index(combination[3]))}"

        # Generate the Excel formula
        formula = (
            f'=IF({n3}=0, "Tidak Lanjut", '
            f'IF({n9}=0, "Tidak Lanjut", '
            f'IF({n14}=0, "Tidak Lanjut", '
            f'IF({n18}=0, "Tidak Lanjut", "Lanjut"))))'
        )

        # Write the formula to the "Rumus" column (column E)
        ws[f"E{row_index}"] = formula

    # Save the workbook
    file_name = "combinations_with_formulas.xlsx"
    wb.save(file_name)
    print(f"Excel file '{file_name}' has been created successfully!")

# Run the function
create_excel_with_combinations()