INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ika setaningrum', 5, 'The ambiance is great for relaxing, hanging out pretty. The drinks are good, Tiramisu Latte (25k) smells good and has a distinctive rum-like flavor too. The service is friendly and informative too, knowing what''s on the menu.
I ordered the chicken rica rice (30k).
+plenty of portions and filling
+ got drumstick, stuffed breast, white rice, fried onion, and pickled cucumber
-the chicken is rather tasteless, when marinating, maybe a little seasoning can be given so that when cooked, not only the outside is “flavored”
-the sauce tends to be sweet, not spicy, it could be that it doesn''t suit my ''spicy'' taste.

My friend ordered the sambal matah chicken rice. The sambal matah was quite good.', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ariyanti Haris', 5, 'Many choices of food and drinks that are up to date, gen z kids will love...
The price is in line with the taste,
Just a shame there are still many who smoke 😅

There''s live music too, so you have to volume up if you want to talk to friends...', 'Group', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Jackly Fiorentina', 4, 'Sobat Kopi is one of the family coffee options in Pare-Pare that has many food options. That''s why it''s crowded.

One of the coffee hits is also here because there are not many other options in Pare-Pare. The toilets are clean, there is a prayer room, and there is a second floor for the first floor which is not too spacious.

It''s just that, the food serving is quite long. I can imagine hungry people coming here. Although the name is “Sobat Kopi”, the vibe is restaurand. Come here to eat, not to have a beautiful coffee.', 'Duo', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Serliy Abd Malik', 4, 'First time coming here, I think the place is comfortable and clean, the location is very strategic in the middle of the city, the staff is also friendly.
For drinks I ordered biscoff milk tea, the picture on the drink menu uses lotus biscuits but when served the lotus biscuits were not there, but in terms of taste it was good. I also ordered a mix platter, the food took a long time to be served, since my friend was in a hurry, I ended up taking it away, in terms of taste I think the potatoes are very good, the sausage is good, I got chiken wings but the taste is a bit sweet, the nuggets are also good.', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nurman Riyadi Rahman', 5, 'Cafenya recommended buat nongkrong sambil ngopi. Makanannya juga enak-enak loh. Cuma tempatnya kesannya agak kecil, klo rame kesannya agak sesak. Bukanya sampai larut malam, bisa jadi opsi buat makan malam sehabis perjalanan panjang dari kampung atau dari kota.', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('blue ranger', 5, 'First visit here because of a recommendation from a friend. White coffee or something similar with that name, highly recommended to try. There is also Nasi Goreng with various variants and all of them are delicious. Fried noodles are also like that. If you want to try both, I recommend trying the Mix Box, it has Fried Rice and Fried Noodles. It''s really delicious. What''s a bit lacking is the Ramen, not really, but it''s normal because it''s not a ramen restaurant. But for everything else, it was very good. For the price, it''s standard cafe price, so it''s still reasonable. The place is comfortable, the toilets are clean, and the waiters are friendly. The parking lot is a bit difficult, but someone directed me to park on the shoulder of the road anyway.', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ashe syamsuddin', 5, 'The location is strategic, the place is quite spacious and comfortable (downstairs). But when arisan visitors come, the atmosphere becomes uncomfortable and very noisy. Just a suggestion, maybe it''s better if the arisan place is separated, not combined with other visitors, because it will disturb other visitors.

The waiter is quite friendly. It''s just the presentation that takes a long time, about an hour of new orders served on the table.

The hot sweet tea we ordered tasted tasteless, no sweetness at all. The klepon ice tasted sweet in my opinion, it made me sick. The fries tasted standard, which is how fries taste. The Singaporean fried noodles actually tasted good, but the texture was too soggy. I think the noodles were cooked too long (over cook), so they became soft.

The price is still pocket-friendly.

Oh yes, an additional suggestion. Maybe it would be nice if the air circulation is considered (no open windows), even though there are several visitors who smoke in the room. This is also quite disturbing to other visitors in addition to the problem of arisan mothers who are noisy for mercy.', 'Beverages', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Rizaldi Nurdiansyah', 5, 'A comfortable place for meetings, gathering with friends. The motorcycle parking lot can accommodate many motorcycles, but cars can only park on the side of the road. There is also gelato here, the menu choices are also diverse, from beverages, desserts, appetizers, to main courses. Only I really regret that in an air-conditioned room there are still people smoking, provided ashtrays as well. Smoking should not be allowed in an air-conditioned room, and a smoking room is provided, but fortunately there is a non-smoking room on the 2nd floor.', 'Group', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('catherina selya', 5, 'Food, drinks are varied. The taste is also good. Comfortable atmosphere for work, there is a non-smoking room on the 2nd floor. 2. The staff is friendly. The location is also strategic. A little difficult to get parking during lunch hours', 'Beverages', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('yuliana rahmawati ', 5, 'Located beside Andi Makkasau field, Cafe sobat kopi offers a wide variety of western food as well as local food.

The prices are a bit more expensive compared to other cafes, but that''s because besides being a nice place, their menu is often updated. So several times there can always order a new menu. There are some menus that are only available at this cafe and as far as I know are not available in other cafes such as salmon teriyaki and dori salted egg. worth to buy for those who are bored with the same menu.

Friendly staff, asking for a baby chair is also delivered by the staff.', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Emm', 4, 'Downstairs is a smoking room, non smoking room is available on the 2nd floor with a smaller area due to sharing with VIP room.

Quite a lot of menu choices, the taste is quite ok. One of the favorite warkop in Pare-Pare.

Gelato is also available here, although the flavor variants are still limited.', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Desy Ramadhani Thamrin', 2, 'The use of the room is air-conditioned but many visitors smoke. Provide a smoking area or reprimand customers who smoke indoors. Because it is very disturbed by cigarette smoke.', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Murfad pasaung', 5, 'Recommended coffee and relaxation place for those passing through the city of pare pare', 'Chill', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('joko suhardiman', 3, 'The service is not good because it seems slow, and the atmosphere is not comfortable to hang out because the space between other customers is too close so it is not private. More like a restaurant than a coffee shop', 'Chill', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('dede rahman', 4, 'The place is fun, the room is comfortable with an eccentric arrangement of table chairs, just parking is less spacious, if the food menu is okay, recommended place if they are relaxing with family, was disappointed because our food was missed until we went home, maybe they were busy, I don''t know, the rest is okay Lah...', 'Duo', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('leony hosanna', 5, 'Rooms are divided into 1st floor smoking room, 2nd floor non-smoking & VIP. Those who do not smoke can use the 2nd floor room.
Dining and drinking menus are varied.', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('kryst', 4, 'including quite often here, but the cafe is not consistent with the food, sometimes it''s good sometimes it''s not. waiting to reserve the food is also sometimes very long. where once observed several people smoking in the air-conditioned room. I swear they just let it go, the employees are not very assertive. they are the ones who enjoy smoking, we are the ones who are suffocating from smoke inhalation.', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('cesar zehan camille', 3, 'One of the contemporary cafes in Parepare. The prices are relatively standard, but the food tastes pretty good. Unfortunately, there are not many seats and the waiters are less compliant with the Covid-19 prokes (often open and close masks and the chef and cashier do not wear masks at all). In addition, there is no differentiated space for guests who smoke and do not smoke so that those who do not smoke will feel uncomfortable ...', 'Food', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('galih prasetyoo', 4, 'The place is quite cozy. Food and beverage prices are competitive', 'Food', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Syamsul irfan', 1, 'One of the cafes in Parepare whose location is quite strategic. The menu choices are many, both food and drinks. But unfortunately, the serving process is relatively long.
Even ordering using on-line motorcycle taxis is not professional, the menu sent does not match. What was ordered was Korean Spicy Chicken, but what was sent was Korean Spicy Ramen. Complaint service also has no solution when contacted. A chaotic and unprofessional restaurant. NOT RECOMMENDED', 'Beverages', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('bayu prabudi', 1, 'Don''t order ramen here if you don''t want to be panked with delicious noodles. Far from ramen, it''s more like tasty noodles. This is my grab order for 40, what I got was delicious noodles. Severe', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('A Muh Idham', 5, 'Fast service, fast food <15 min, clean, comfortable, most importantly, good food and drinks at affordable prices in the pocket.', 'Beverages', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Kartini Marjuni', 5, 'The most recommended place. clean, comfortable, air-conditioned, live music facilities, delicious menus, pocket-friendly prices, and a very strategic location...', 'live music', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Bornfreeonelove', 1, 'I don''t know if I''m judging badly.  Because people''s judgment is different.  I''m most lazy to wait for food.  Ordered at 7.40 and by 8.25 it hasn''t arrived yet.  It''s not very crowded.  I want to jump into the kitchen to cook. It''s very slow when it''s a man who cooks.', 'Group', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Baskoro', 5, 'This was my first visit here for breakfast before starting the umkm training activities.
Working as an MSME Business Consultant makes me often travel to various places in Indonesia.', 'Working', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Asyudi Anggara', 4, 'Cozy atmosphere to relax either alone or with family/relatives', 'Alone', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('ant75', 4, 'A pretty good place to hang out, social gathering, business meeting, birthday party, etc.', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ardi Dadang', 5, 'Now if you are in Parepare city square. Simply cross the road and you can enjoy Premium Coffee at a price that is fairly affordable for millennials. Live music at night is a special entertainment for visitors who come. Luxurious facilities further support the display of social media stories. If you enter the Parepare city area, for me, you must come here.', 'Night', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Andhy Bilal', 5, 'Good service, good food, affordable prices, good toilet cleanliness, live music, there is a prayer room but small', 'live music', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Andi Zulkifli', 3, 'The palm sugar coffee is delicious, with croisan. It''s rare to find a cafe that sells croisan bread.', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Adnan Mahfud', 1, 'Was going to eat here with family but canceled because the air-conditioned non-smoking room on the 1st floor even smells of cigarette smoke. There are 2 visitors casually smoking even though there are also children there. Please the cafe manager can direct visitors who smoke to outside or on the 2nd floor.', 'Duo', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Bhismar Shardin', 4, 'the place is not bad,... cmn the table is not too much,. but not friendly for people who don''t smoke,', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Arya', 1, 'The service is very bad, starting from the bad clinging service, you have been told to order even though the table is still dirty, it is not really cleaned properly, and I really don''t like the service, I was told to wait an hour for my food to not come.', 'Food', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Idham Jufri', 5, 'The most comfortable hangout place with a varied and classy menu, super friendly service', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('nurfitriana kasa', 3, 'The place is good. The food is subjective well according to taste. Yesterday''s order of fried dry noodles was not as good as my expectations but the fried rice was really good, the sambel ijo nasgor was just so-so. The drinks are also just so so. Service may be good when we dtg only the waffle menu ordered is not according to order well. Order chocolate waffle brought vanilla. Employees explain it is not clear. They said they put the order into the system but the customer chooses what flavor. Well, we ordered chocolate, clearly on the receipt also printed chocolate waffle but they have no intention to change the order. And again, the menu that we ordered was given to a new customer when we had been waiting for a long time. Please, the employees should focus on what table to bring the order to. DON''T COME JUST SHOUTING THE NAME OF THE MENU BUT DON''T KNOW WHO ORDERED WHAT TABLE AND WHO ORDERED FIRST. The food took quite a long time to be served or maybe it was because there were many customers also because yesterday the situation happened when I came. That''s all', 'Beverages', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Rudi Spiderman Hartono', 5, 'Aku kalau kesini pasti pesan nasi goreng. Nasi gorengnya dahsyat', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Jessica Wongso Putri', 5, 'The food is good and cheap for a cafe. The food varies from pastries to gelato. There is a non-smoking room upstairs. Every time I come here, it''s never empty, the service and food served are relatively fast.', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Naufal Wardi', 5, 'Very good for culinary tours, refreshing shopping etc. with family', 'Duo', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Sri Mulyati', 4, 'The place is cozy... The food is good... the price is affordable... But it takes a long time...', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Paramita Rusli', 5, 'The place is cool because it is air-conditioned so it is suitable for social gatherings and there are many choices of menus too.', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Rasya Islami Rahman', 1, 'I visited on the night of 1/6/2023 around 20.00wita we just entered the atmosphere was less pleasant due to the large number of people smoking cigarettes even though the place was an air-conditioned room and also in my opinion the service was not good such as waiters who shouted and also food that was under pacing from the 2nd floor back down to the 1st floor. And what I think is most disappointing is the black burger that did not come to our place at first we asked but the waiter just said please wait so we waited but when we finished eating the burger had not come and when we wanted to cancel the burger the waiter said that the burger had been made but because we were already disappointed with the waiter we still canceled the burger that did not come from the beginning we ordered until we wanted to go home maybe in my opinion it can be improved in terms of service and the use of cigarettes in the room using air conditioning.', 'Night', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('itha subu', 4, 'The food is delicious n the waiters are quite friendly', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ang rikwanto', 5, 'The indoor atmosphere of the cafe is quite good, food and drinks are also varied.', 'Beverages', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('baso yusuf', 4, 'Everything is okay, it''s just that there should be a smoking room so that it doesn''t merge with the public dining area.', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('feryanto jong', 1, 'The employee was asked even answered nyolot, ordered fried noodles coffee buddy from 19:20 to 20: 22 blm so, first came quiet after I ordered began to arrive guests, but why did they come first even though I came first no problem with the reservation that I had a problem with before So it''s the guests where I came first I ordered from them, what''s more, just order fried noodles coffee buddy, the leader must correct, I suspect the stove is only 1 so it takes a long time to cook badly! !!!!  Correction of performance, order anything for more than 1 hour, the worst is ordering udon noodles that look like instant noodles cmn given bakso bakso suki, amazingly long, where when it''s finished, we were told to eat it quickly because 10 minutes want to stay, bad !!!!', 'Coffee', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Yudha Prakasa', 5, 'An Instagrammable place suitable for young people', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Devantie Ardilawanti', 4, 'The food is quite varied,, only the service is a bit long', 'Food', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Anshor Muhajir', 5, 'This is a new cafe in Parepare. The place is cozy and clean, the menu is plentiful and the taste is quite good. The menu ranges from heavy meals to light snacks. The 2nd floor has a room that can be rented out for events/meetings. The parking lot is quite spacious. Anyway, it''s comfortable to hang out at this cafe.', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Yongki Chandra', 2, 'This is a new cafe in Parepare. The place is cozy and clean, the menu is plentiful and the taste is quite good. The menu ranges from heavy meals to light snacks. The 2nd floor has a room that can be rented out for events/meetings. The parking lot is quite spacious. Anyway, it''s comfortable to hang out at this cafe.', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Iskandar Faisal', 4, 'Quite a hangout place...but it is quite noisy from visitors talking, calling in the room....so it disturbs the peace around it.', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Parlan parlan', 5, 'Strategic location and clean and comfortable', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Kamar Pixel', 4, 'Always good, coffee buddy.', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Maryam Umma Faeyza', 5, 'for food, enaak', 'Food', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('dela man', 1, 'one of the waiters was not very friendly.
The way he told the customer about the smoking ban in the air-conditioned room was very annoying.', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('iwan one one', 3, 'The most relaxing place away from the noise', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('abidin smile', 5, 'cozy place', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Vanzidh 48', 5, 'The place is cozy and comfortable, the food is delicious and the coffee is okay for hanging out.', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Muhammad Ali Akbar', 5, 'The place is comfortable and clean, the service is quite fast, the bathroom is also clean ...
The price problem in my opinion is worth it ...
No problem at all ...
Recommended👍👍👍', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Fitri Amiq', 3, 'The place is nice and the waiter is friendly..but the order is always slow to come even though it''s just an order of meatballs, I''ve been to coffee buddy twice.
Hopefully it can be a concern so that it can survive amid the development of warkop in Parepare. Success SOBAT KOPI', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('ANRASTRYASTUTI 2023129001', 1, 'The waiter was not friendly, the mistake of issuing a receipt before inputting the discount was used as an excuse to say that the card type did not match.', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Trian Fisman', 1, 'The price is relatively cheap for such a cozy place.', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nur Hijaya', 5, 'The food is delicious...cozy atmosphere and friendly service', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Rey Gaspresz', 5, 'Good food menu, air-conditioned room and crowded... comfortable and at home in Sobat Kopi... Kereen👍👍👍👍👍', 'Group', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hizbuddin Dj', 5, 'An elite and romantic coffee, lunch or dinner spot in the city of Parepare. Great.', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Lazora Spanlansani', 1, 'Long service. Rest hours are forgotten just to wait for orders', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('ahber simantupang', 1, 'The employees are friendly and welcoming. Great atmosphere to hang out with friends or family. recommended anyway.', 'Duo', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nur Umniyyah Mustaman', 1, 'Order delivery, the admin is annoying .. said the fare was 9k, the courier charged 10k.', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Owen Khosman', 1, 'The place is nice but the service is not optimal. My order of fried noodles took 1 hour to come out. ☹️☹️', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Andi ahmad afandi', 1, 'The food and drink menu is great.
The atmosphere is cool.', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Arahman Ramadhan', 4, 'There is only one shortage of parking space.', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Abul A''la', 3, 'food, standard service. Nice place', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Dina mu', 5, 'recommended food and service! spacious place and there is live music', 'live music', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Difah H', 1, 'Online service no response want to make a reservation just read it brought the real star', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ajeng Cahya Purnama Sari', 3, 'The food took a long time to arrive. I ordered first, but someone else''s order came first.', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Mulya 99', 5, 'I really like the contemporary atmosphere 😊😊😊😊😊 ', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Fauziah Ahmad', 5, 'Cozy, good menu', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Gagal Sarjana Chanel', 5, 'cool anyway', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('muhammad daud', 5, 'Nice, friendly, just a little cramped', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Oeij Dedy Kwandy', 5, 'Fun place... best price
Smokers friendly... 👍 ', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hendra Supriadi', 4, 'Really cool place, food is also up to date', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nasira Ananda Y', 5, 'Food choices are plentiful. Comfortable atmosphere.', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nurbaety Samsul', 5, 'all the menus are delicious,, recommended', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nataniel Tangdilian', 5, 'Good. Variety of menu', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Jacky Gunawan Ho', 1, 'The order took too long even though I only ordered indomie for almost an hour and a half.', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hasdar Malla', 3, 'People smoking in air-conditioned rooms is not prohibited', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Yuliaa Darwis', 1, 'Slow service and standard menu', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('M Jasri ', 5, 'A strategic place and a cool place make this place comfortable to hang out.', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Irwan Putra', 5, 'Recommended for coffee lovers', 'Coffee', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('plope Nandi ', 2, 'The back sound is too loud, so we have to shout a bit when we talk.', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Tlses 666', 1, 'The social media admin is slow to respond.
Even though online lo wkaka', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Uull Darullah ', 5, 'Great coffee buddy...
A recommended coffee hangout.', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Muhammad Rizal Ar', 5, 'the food is good ... but the wait is long', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Yerry januar', 5, 'The coolest cafe in pare2, affordable price', 'Chill', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Musdin Official', 4, 'On Jalan Veteran, just behind Yamaha Motor Parepare. The place is cool', 'Chill', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Husain sayadi', 5, 'The room is air-conditioned, food and drinks are great', 'Beverages', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('BASNUR RUSLI', 5, 'The most fun places to eat and hang out', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Sahatmarasi Siregar ', 5, 'parking lot', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Fatma aulian', 4, 'It''s clean and the staff is friendly...', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Agung setia nugraha', 5, 'Eat in', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('ilham bakran', 5, 'The food is pretty good', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Abdul gafur', 5, 'Fried noodlesx..delicious..there is ice cream gelato...', 'Food', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Yusmawan', 5, '👍 …', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hany Chandra', 5, 'The food and coffee are great... 👍 ...', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('rihalya melcy patandean', 4, 'If you''re a coffee buddy. Remember the word “beautiful”', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nonnie wahyuni', 5, 'Not a bad place to hang out', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Arifin Mrm', 4, 'The coffee is good... Cozy atmosphere', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Gusy Operafuky', 5, 'Many menu options', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Andi Firman Mubarak', 5, 'Good service, good food', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Siti Ainun Sri Rezly', 1, 'The service is very long', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Riry Abidin', 1, 'Slow down...', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('ninie darniati', 3, 'Good coffee, small space', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('umi hani', 5, 'Great all the menus', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Risang Aji', 5, 'the snacks and sweet potato fries are delicious', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Tony sikku', 5, 'The coffee is good', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Yusmur Rusman', 5, 'Very friendly service', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Sapril hadenan', 5, 'Steady', 'Beverages', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('RATMI', 5, 'Delicious, cool, affordable price', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('mustamal akbar', 5, 'Romantic atmosphere in this place', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Bastian Basri', 3, '👍 …', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Fitri noval', 5, 'The service is very good👍👍👍👍👍 ', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('inayatullah jusuf elere', 4, 'Steady', 'Beverages', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nina Nur', 3, 'Cozy', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Fendi77', 5, 'Delicious ', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nurmala Sari', 5, 'cozy place', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Andi Riky', 4, 'mantul', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Syamsul SSi MM CIR CPS', 4, 'Recommendedd', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Akbar Al Mkassari', 3, 'Eat in', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Piet scar', 5, 'Mantul', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('fifit puguh', 5, 'Steady', 'Beverages', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Syahril Ningki', 5, 'Wawww tempt nongrok fun dipare pare good food affordable and service top markotop pokokx guaranteed steady if you go to pare nga fun if you do not hang out here like the atmosphere and service very much', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Afandy HR', 3, 'The food tasted so-so. It was a bit of a surprise that they served my ramen with utensils 😆. My first time eating ramen with a fork & spoon. The atmosphere is cozy but I think there needs to be more privacy for individuals, meaning their table spacing is closed.', 'Alone', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('octopus ', 4, 'Other than the parking lot being too crowded (I recommend not coming on weekends), this place is great! The food is fresh and doesn''t take much time to serve.

It''s also better to book a table in advance so you don''t have to wait in line!', 'Group', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Anisti R.Rahardjo', 4, 'But yeah, a bit annoyed by people smoking in air-conditioned rooms.
If I had known beforehand, I would have asked which one was for non-smoking rooms.', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Harta Madia Kusumah', 5, 'They have good coffee and a nice atmosphere. The price is still affordable. And it has live music too. Overall a good experience. Non-smoking rooms and vip rooms are located on the 2nd floor.', 'Coffee', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Emilio', 4, 'Welcome to the magical world of Sobat Kopi, where European style blends with the delicious essence of Indonesia! This place is a culinary paradise that will make you exclaim "Wow!" with every bite. Don''t let the name fool you, you''ll find more than just coffee here.


If you''re as hungry as a wolf, don''t worry! You will be able to immerse yourself in a kaleidoscope of flavors, from unforgettable hamburgers to avocado and eggs, making your tongue dance as if it were at a rave. And we can''t even begin to describe the drink options - from traditional Indonesian dishes to the wonders of various types and flavors.


The atmosphere is a feast for the eyes and ears. If you want to move, an evening with friends turns into an epic adventure, accompanied by live acoustic tunes. And if you want to relax with family, the hospitality of the entire staff at this place will envelop you like a soft blanket.


Ah, the price! For tourists, it''s like finding a hidden treasure, whose goodness doesn''t significantly impact the wallet. However, remember, for those of you with a little inherited wealth, Sobat Kopi can be your daily refuge. However, we all know that every bite, every sip, and every note is worth every penny.


In short, Sobat Kopi is a blend of culture, flavor, and pleasure. A captivating blend of Europe and Indonesia, where extraordinary food and tempting drinks are just the beginning of an experience not to be missed. It doesn''t matter if you''re a hungry adventurer or a dreamer seeking soothing tunes - this place is the answer to every desire. Go, taste, and enjoy the journey!', 'Evening', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nico Kaan', 5, 'A comfortable and cool cafe with a diverse menu. Pleasant and quick service.  It''s a pity the food was cold.', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('A. Rajindra Pratama', 5, 'A great place to hang out, have lunch, or just eat. They have a lot of affordable menu options, a smoking area, and the best ice cream they have.', 'Chill', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Athar Abdurrahman', 5, 'This is a cozy café, even though many people smoke indoors, we didn''t notice it because the ventilation system is good.', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('islamey arifin', 5, 'The place is okay, the food is delicious.', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hendri Ardian', 5, 'The place is comfortable and cozy, the food is delicious, and the service is friendly.', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Local Media Enthusiast', 5, 'Cold, but crowded', 'Group', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Saharuddin Nasrum', 5, 'Delicious food & place', 'Food', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('eldi amrillah', 3, 'The serving time was not very good.', 'Umum', 'Negatif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hariyanto Chairun', 4, 'Comfortable, but has a small parking area.', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Rian Muhaji', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES (' Mustafe Kemal Sahdi', 5, 'oke', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('swastamita', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hendra saputra', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Muhammad Iqbal', 5, 'stendy', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('mimi rahman', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('ayu kayin', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Dinul Haq Qayyim Daud', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Rio Rezki Saputra', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Suci Ramadhan', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Muhlisanto santo', 4, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Tester marker', 5, 'good', 'Umum', 'Positif', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Mochammad Faizal', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Jemson ciayadi', 5, 'oke', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('A. ibnu malik', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('nabila aila', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Uswatun Hasanah', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nasrullah', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Muhammad Fadil', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Muhammad fadil', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nana Diana', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Feramitha23', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Gaton subroto', 5, 'oke', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('andi taufik', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Dirman DJ', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Agam Satria', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Sul 86', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Dota travel', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('cahaya tantri', 5, 'Eating on-site...', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Dyah Nur Pratiwi', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Anto Mard', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('HMkardi', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Andi Samsinar', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('NurdhinN shuckers', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Prayudi', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hasni yana fajria', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('R. Ibnu Hadjar Achmady', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Mas Asho', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Indra R2', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('siti hadijah', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('joe', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hasril', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('FuadFebriantoSecar10', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Busrah Adrian', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Arini Rini', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Mentaei aura prisianda', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Gede Kusuma parta', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Saenal Lovers', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Misfahul fahal', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('yuli afdal', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('ahmadfqraa', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hendry Gosal', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Trisno Alvin', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Makhadir Hasli', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ferry Noor Alamsyah', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('nurwahidah syariff', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('ekawati ibrahim saleh', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('rian martawijaya', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('ardi tanugraha', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hasriana titk', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hasviranda alfairah', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Darwis Latif', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('lufy taro', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('muslinda muin', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('f a', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('syahrullah hamzah', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('ilyas alimuddin', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('andi zullkifli', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('syaiful  Mahasan', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Agyats Amalia', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('M syarifuddin', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nurfiriana said', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Fanny Gunawan', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Safaruddin safar', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('lilyanti lily', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('rahun rl', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('mustafa kaan ', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('andi muhammad yusuf', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Muchandar albour''i', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Aslam Lukman', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Lapni Chandra', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Taufiq Muh Amir', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Amanda', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Chaidir Fadhil', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Andi Abdullah', 5, 'Makan di tempat', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('EMHA ABHY', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Penjahit Evi', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Zain uddin', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ansar Rasak', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('ilmi ariesta', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Randi Kurniawan', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Marwan Ali', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Muhammad Agus', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Alvin Vivo y20s', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Wilson Citro', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Caroline Chandean', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Indah yuliani23', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Mhikayla mathar', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Eka Mualana Usman', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Indra Guna', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Andirika Rikachaca', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ajeng Djoeddawi', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('andi jayanti', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ashi wahyuni', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Awali ali', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Tri Hantoni', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('SatuKosong', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Hilmy Ibrahim', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Harjuno Usis', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Baharuddin mide', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Syauqi Milanisti', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Yuka Tamada', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('irfan gelo', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Andi Muhlis A28b', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('sary monalisaa', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ira Lestari', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Bacox Bhaaruddin', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Herie Jweleq', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Winda Hatta', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Arifin Rahim', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ham Fadil', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Eoneulika 2512', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Ayu s Bukaka', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Nuravmi 2304', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Rahmad Zacky (Chronizz)', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Surya Indrawati', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Rahmawati Nurlitasari', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Syawal F itra', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Vivi Ratu', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Adrian Syah', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Fadly Ruslan', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Risma Eka 13', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Asnora Nora', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Raya Motor', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Citra Damayanti', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('akbar tekinfo', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Julinda Astri Utari', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('muhammad taufan', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Reza Muin', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Andi Agus', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('alman allung', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Bitol', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Where''s Anthiraan?', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Muhammad Fajriansyah sudirman', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');
INSERT INTO reviews (nama_pengulas, rating_bintang, teks_ulasan, topik_utama, sentimen, nama_cafe) VALUES ('Kartika Ika Putri', 5, '-', 'Umum', 'Netral', 'Sobat Coffee');